<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="1" failures="0" skip="0"><testcase classname="tests.test_helpers.HelpersTestSuite" name="test_audiobook_class" time="0.002"><error type="builtins.NameError" message="name 'Audiobook' is not defined"><![CDATA[Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 593, in run
    self._callTestMethod(testMethod)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/Users/federico/Documents/git/python-audiobook-tools/tests/test_helpers.py", line 8, in test_audiobook_class
    audiobook1 = Audiobook('~/tests/fixture/audiobook1.m4a')
NameError: name 'Audiobook' is not defined
]]></error></testcase></testsuite>